<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="css/normalize.css" />
		<link rel="stylesheet" href="css/main.css" />
		<title>Classic Models</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
		<!-- 			<li> <a href="home.php"> Accueil</a> </li>
					
					<?php if (isset($_SESSION['iduser'])): ?>
			
					<?php
						$me = getUserById($_SESSION['iduser']);
					?>
					<li>Bonjour <?= $me['firstname'] ?> <?= $me['lastname'] ?></li>

					<li><a href="logout.php">Se déconnecter</a></li>

					<?php else: ?>
					
					<li><a href="login.php">S'identifier</a></li>

					<?php endif; ?>
					<li> <a href="panier.php"> Panier</a> </li>
					<?php 
					$ProductCartNumber = count($_SESSION['cart']);
					echo $ProductCartNumber ;
					?> -->
		
				</ul>
			</nav>

		
		</header>
		