<?php 
include '../views/header.phtml'; 
?>

<main>
	<h1>Bons de commande</h1>
	<a href="orders.php">Retourner à l'accueil</a>

	<section>
		<h2><?= $customer["customerName"] ?></h2>
		<h3><?= $customer["contactFirstName"] ?> <?= $customer["contactLastName"] ?></h3>
		<p><?= $customer["addressLine1"] ?> </p>
		<p><?= $customer["addressLine2"] ?> </p>
		<p><?= $customer["city"] ?> </p>
	</section>
	<table>
		<caption>Bon de commande n°<?= $orderNumber ?></caption>
		<thead>
			<tr>
				<th>Produit</th>
				<th>Prix Unitaire</th>
				<th>Quantité</th>
				<th>Prix Total</th>				 	 	
			</tr>
		</thead>
		<tbody>
		<?php $ht = 0; $TTC = 0; $tva = 0; ?>
		<?php foreach ($orderDetails as $orderDetail): ?>
			<tr>
				<td><?= $orderDetail["productName"] ?></td>
				<td><?= $orderDetail["priceEach"] ?>€</td>
				<td><?= $orderDetail["quantityOrdered"] ?></td>
				<td><?= $orderDetail["prixTotal"] ?>€</td>	
			</tr>
			<?= $ht += $orderDetail["prixTotal"] ?>
		<?php endforeach; ?>	
		
		</tbody>
		<tfoot>
			<tr> </tr>
			<tr>
				<td> Montant Total HT </td> 
				<td> </td>
				<td> </td>
				<td> <?= $totalHT = $ht ?>€</td>

			</tr>
			<tr>
				<td> TVA 20% </td> 
				<td> </td>
				<td> </td>
				<td><?=$tva=$totalHT*1.2-$totalHT ?>€</td>
			</tr>
			<tr>
				<td> Montant Total TTC </td> 
				<td> </td>
				<td> </td>
				<td><?=$TTC=$totalHT*1.2 ?>€</td>
			</tr>
		
		</tfoot>




	</table>



</main>

<?php 
include '../views/footer.phtml'; 
?>
