<?php 
include '../views/header.phtml'; 
?>

<main>
	<h1>Bons de commande</h1>
	<h2>Liste de commandes</h2>
	<table>
		<thead>
			<tr>
				<th>Commande</th>
				<th>Date de la commande</th>
				<th>Date de livraison</th>
				<th>Statut</th>				 	 	
			</tr>
		</thead>
		<tbody>
			<?php foreach ($ordersList as $order): ?>
			<tr>
				<td><a href = "orderdetails.php?orderNumber='<?= $order["orderNumber"] ?>'"><?= $order["orderNumber"] ?></a></td>
				<td><?= $order["orderDate"] ?></td>
				<td><?= $order["shippedDate"] ?></td>
				<td><?= $order["status"] ?></td>
			</tr>
			<?php endforeach; ?>
		</tbody>




	</table>

</main>

<?php 
include '../views/footer.phtml'; 
?>
